// All Fortaleza CE neighborhoods and location data
export const FORTALEZA_NEIGHBORHOODS = [
  'Aldeota',
  'Meireles',
  'Benfica',
  'Papicu',
  'Cocó',
  'Messejana',
  'Parangaba',
  'Montese',
  'Centro',
  'Dionísio Torres',
  'Fátima',
  'Varjota',
  'Cidade dos Funcionários',
  'Água Fria',
  'Antônio Bezerra',
  'Bom Futuro',
  'Cambeba',
  'Castelão',
  'Damas',
  'Edson Queiroz',
  'Engenheiro Luciano Cavalcante',
  'Floresta',
  'Granja Lisboa',
  'Guararapes',
  'Iguatemi',
  'Itaperi',
  'Jangurussu',
  'José Bonifácio',
  'Lagoa Redonda',
  'Luciano Cavalcante',
  'Maraponga',
  'Mondubim',
  'Mucuripe',
  'Parque Dois Irmãos',
  'Passaré',
  'Pici',
  'Praia de Iracema',
  'Quintino Cunha',
  'São João do Tauape',
  'Serrinha',
  'Siqueira',
  'Tauape',
  'Vila União',
] as const

// Approximate coordinates for major Fortaleza neighborhoods (lat, lng)
export const NEIGHBORHOOD_COORDINATES: Record<string, { lat: number; lng: number }> = {
  Aldeota: { lat: -3.7358, lng: -38.5069 },
  Meireles: { lat: -3.7256, lng: -38.5053 },
  Benfica: { lat: -3.7450, lng: -38.5461 },
  Papicu: { lat: -3.7400, lng: -38.4900 },
  Cocó: { lat: -3.7494, lng: -38.4895 },
  Messejana: { lat: -3.8312, lng: -38.4950 },
  Parangaba: { lat: -3.7797, lng: -38.5600 },
  Montese: { lat: -3.7650, lng: -38.5650 },
  Centro: { lat: -3.7275, lng: -38.5311 },
  'Dionísio Torres': { lat: -3.7456, lng: -38.5112 },
  Fátima: { lat: -3.7650, lng: -38.5350 },
  Varjota: { lat: -3.7244, lng: -38.5150 },
  'Cidade dos Funcionários': { lat: -3.7950, lng: -38.4900 },
  Mucuripe: { lat: -3.7175, lng: -38.4800 },
  Tauape: { lat: -3.7600, lng: -38.5000 },
  Guararapes: { lat: -3.7750, lng: -38.5050 },
  Maraponga: { lat: -3.8050, lng: -38.5850 },
}

// Default center for Fortaleza map
export const FORTALEZA_CENTER = { lat: -3.7172, lng: -38.5433 }
export const FORTALEZA_DEFAULT_ZOOM = 12

export const BRAZIL_STATES = [
  { value: 'AC', label: 'Acre' },
  { value: 'AL', label: 'Alagoas' },
  { value: 'AP', label: 'Amapá' },
  { value: 'AM', label: 'Amazonas' },
  { value: 'BA', label: 'Bahia' },
  { value: 'CE', label: 'Ceará' },
  { value: 'DF', label: 'Distrito Federal' },
  { value: 'ES', label: 'Espírito Santo' },
  { value: 'GO', label: 'Goiás' },
  { value: 'MA', label: 'Maranhão' },
  { value: 'MT', label: 'Mato Grosso' },
  { value: 'MS', label: 'Mato Grosso do Sul' },
  { value: 'MG', label: 'Minas Gerais' },
  { value: 'PA', label: 'Pará' },
  { value: 'PB', label: 'Paraíba' },
  { value: 'PR', label: 'Paraná' },
  { value: 'PE', label: 'Pernambuco' },
  { value: 'PI', label: 'Piauí' },
  { value: 'RJ', label: 'Rio de Janeiro' },
  { value: 'RN', label: 'Rio Grande do Norte' },
  { value: 'RS', label: 'Rio Grande do Sul' },
  { value: 'RO', label: 'Rondônia' },
  { value: 'RR', label: 'Roraima' },
  { value: 'SC', label: 'Santa Catarina' },
  { value: 'SP', label: 'São Paulo' },
  { value: 'SE', label: 'Sergipe' },
  { value: 'TO', label: 'Tocantins' },
]
